/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.CuartelData;
import Entidades.Emergencia;
import java.util.ArrayList;
import AccesoADatos.EmergenciaData;
import Entidades.Cuartel;

public class AgregarBrigada extends javax.swing.JDialog {

    public void cargarComboboxEspecia() {

        EmergenciaData emergenciaData = new EmergenciaData();
        ArrayList<Emergencia> listaEmergencia = new ArrayList<>();
        listaEmergencia = emergenciaData.listarEmergencia();
        for (Emergencia eme : listaEmergencia) {
            ComboBoxEspecialidad.addItem(eme.getEmergencia()
            );
        }
        
        CuartelData cuartelData = new CuartelData();
        ArrayList<Cuartel> listaCuartel = new ArrayList<>();
        listaCuartel = cuartelData.listarCuarteles();
        for (Cuartel cuartel : listaCuartel) {
            jComboBoxCuartel.addItem(cuartel.getNombreCuartel());
        }
                
    }

    /**
     * Creates new form AgregarBrigada
     */
    public AgregarBrigada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarComboboxEspecia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNombre = new javax.swing.JLabel();
        JLEspecialidad = new javax.swing.JLabel();
        JLCuarel = new javax.swing.JLabel();
        jBGuadar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        JTFNombre = new javax.swing.JTextField();
        ComboBoxEspecialidad = new javax.swing.JComboBox<>();
        jComboBoxCuartel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        JLNombre.setText("Nombre");

        JLEspecialidad.setText("Especialidad");

        JLCuarel.setText("Cuatel");

        jBGuadar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-guardar-50.png"))); // NOI18N
        jBGuadar.setText("Guardar");
        jBGuadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuadarActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salir-50.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        JTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreActionPerformed(evt);
            }
        });

        ComboBoxEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEspecialidadActionPerformed(evt);
            }
        });

        jComboBoxCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCuartelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLCuarel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLEspecialidad)
                            .addComponent(JLNombre)
                            .addComponent(jLabel1))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCuartel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jBGuadar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jBCancelar)
                        .addGap(33, 33, 33)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNombre)
                    .addComponent(JTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLEspecialidad)
                    .addComponent(ComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLCuarel)
                    .addComponent(jComboBoxCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuadar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void JTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNombreActionPerformed

    private void ComboBoxEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEspecialidadActionPerformed


    }//GEN-LAST:event_ComboBoxEspecialidadActionPerformed

    private void jComboBoxCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCuartelActionPerformed


    }//GEN-LAST:event_jComboBoxCuartelActionPerformed

    private void jBGuadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuadarActionPerformed
       
    }//GEN-LAST:event_jBGuadarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxEspecialidad;
    private javax.swing.JLabel JLCuarel;
    private javax.swing.JLabel JLEspecialidad;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JTextField JTFNombre;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuadar;
    private javax.swing.JComboBox<String> jComboBoxCuartel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
