/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BrigadaData;
import AccesoADatos.EmergenciaData;
import AccesoADatos.SiniestroData;
import Entidades.Brigada;
import Entidades.Siniestro;
import javax.swing.JFrame;

/**
 *
 * @author Gregorio
 */
public class CerrarSiniestroPuntuacion extends javax.swing.JDialog {

    private int idSiniestro;

    /**
     * Creates new form CerrarSiniestroPuntiacion
     */
    public CerrarSiniestroPuntuacion(java.awt.Frame parent, boolean modal, int idSiniestro) {
        super(parent, modal);
        initComponents();
        botones.add(jRadioButton2);
        botones.add(jRadioButton3);
        botones.add(jRadioButton12);
        botones.add(jRadioButton13);
        botones.add(jRadioButton14);
        botones.add(jRadioButton15);
        botones.add(jRadioButton16);
        botones.add(jRadioButton17);
        botones.add(jRadioButton18);
        botones.add(jRadioButton19);
        this.idSiniestro = idSiniestro;
        cargarSiniestro();
    }
    
    public void cargarSiniestro(){
        
        if(idSiniestro != -1){
            SiniestroData siniestroData = new SiniestroData();            
            Siniestro siniestro = siniestroData.siniestroPorID(idSiniestro);
            BrigadaData brigadaData = new BrigadaData();
            
            
            jLFecha.setText(siniestro.getFecha().toString());
            jLID.setText(siniestro.getCodigo()+"");
            jLEmergencia.setText(siniestro.getTipoEmergencia().getEmergencia());
            jLX.setText(siniestro.getCoordX()+"");
            jLY.setText(siniestro.getCoordY()+"");
            
            Brigada brigada = brigadaData.brigadaPorId(siniestro.getCodBrigada());
            jLBrigada.setText(brigada.getNombreBrigada());
            
            jLDetalle.setText(siniestro.getDetalles());
        }
        
    }

    private CerrarSiniestroPuntuacion(JFrame jFrame, boolean b) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLID = new javax.swing.JLabel();
        jLEmergencia = new javax.swing.JLabel();
        jLX = new javax.swing.JLabel();
        jLY = new javax.swing.JLabel();
        jLBrigada = new javax.swing.JLabel();
        jLDetalle = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Siniestro");
        setPreferredSize(new java.awt.Dimension(640, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID siniestro:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tipo de emergencia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Coordenadas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("X:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Brigada:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Detalles:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Y:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLFecha.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLFecha.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 294, -1));

        jLID.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLID.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 124, -1));

        jLEmergencia.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLEmergencia.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 463, -1));

        jLX.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLX.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLX, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 94, -1));

        jLY.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLY.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLY, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 141, -1));

        jLBrigada.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLBrigada.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLBrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 525, -1));

        jLDetalle.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLDetalle.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 594, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Fecha resolucion: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 244, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Calificacion de exito:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 437, -1, 30));

        jRadioButton2.setText("1");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jRadioButton3.setText("10");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Finalizar Siniestro");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 590, 20));

        jRadioButton12.setText("2");
        getContentPane().add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jRadioButton13.setText("3");
        getContentPane().add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jRadioButton14.setText("4");
        getContentPane().add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jRadioButton15.setText("5");
        getContentPane().add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jRadioButton16.setText("6");
        getContentPane().add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jRadioButton17.setText("7");
        getContentPane().add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        jRadioButton18.setText("8");
        getContentPane().add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        jRadioButton19.setText("9");
        getContentPane().add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-más-50.png"))); // NOI18N
        jButton1.setText("Cerrar Siniestro");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CerrarSiniestroPuntuacion dialog = new CerrarSiniestroPuntuacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLBrigada;
    private javax.swing.JLabel jLDetalle;
    private javax.swing.JLabel jLEmergencia;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLX;
    private javax.swing.JLabel jLY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
