/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BrigadaData;
import AccesoADatos.EmergenciaData;
import AccesoADatos.SiniestroData;
import Entidades.Brigada;
import Entidades.Siniestro;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gregorio
 */
public class CerrarSiniestroPuntuacion extends javax.swing.JDialog {

    private int idSiniestro;

    /**
     * Creates new form CerrarSiniestroPuntiacion
     */
    public CerrarSiniestroPuntuacion(java.awt.Frame parent, boolean modal, int idSiniestro) {
        super(parent, modal);
        initComponents();
        botones.add(jRB1);
        botones.add(jRB10);
        botones.add(jRB2);
        botones.add(jRB3);
        botones.add(jRB4);
        botones.add(jRB5);
        botones.add(jRB6);
        botones.add(jRB7);
        botones.add(jRB8);
        botones.add(jRB9);
        this.idSiniestro = idSiniestro;
        cargarSiniestro();
    }

    public void cargarSiniestro() {

        if (idSiniestro != -1) {
            SiniestroData siniestroData = new SiniestroData();
            Siniestro siniestro = siniestroData.siniestroPorID(idSiniestro);
            BrigadaData brigadaData = new BrigadaData();

            jLFecha.setText(siniestro.getFecha().toString());
            jLID.setText(siniestro.getCodigo() + "");
            jLEmergencia.setText(siniestro.getTipoEmergencia().getEmergencia());
            jLX.setText(siniestro.getCoordX() + "");
            jLY.setText(siniestro.getCoordY() + "");

            Brigada brigada = brigadaData.brigadaPorId(siniestro.getCodBrigada());
            jLBrigada.setText(brigada.getNombreBrigada());

            jLDetalle.setText(siniestro.getDetalles());
        }

    }

    private CerrarSiniestroPuntuacion(JFrame jFrame, boolean b) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        botones = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLID = new javax.swing.JLabel();
        jLEmergencia = new javax.swing.JLabel();
        jLX = new javax.swing.JLabel();
        jLY = new javax.swing.JLabel();
        jLBrigada = new javax.swing.JLabel();
        jLDetalle = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDCFecha_resol = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jRB1 = new javax.swing.JRadioButton();
        jRB10 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRB2 = new javax.swing.JRadioButton();
        jRB3 = new javax.swing.JRadioButton();
        jRB4 = new javax.swing.JRadioButton();
        jRB5 = new javax.swing.JRadioButton();
        jRB6 = new javax.swing.JRadioButton();
        jRB7 = new javax.swing.JRadioButton();
        jRB8 = new javax.swing.JRadioButton();
        jRB9 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Siniestro");
        setPreferredSize(new java.awt.Dimension(640, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID siniestro:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tipo de emergencia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Coordenadas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("X:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Brigada:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Detalles:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Y:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLFecha.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLFecha.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 294, -1));

        jLID.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLID.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 124, -1));

        jLEmergencia.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLEmergencia.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 463, -1));

        jLX.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLX.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLX, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 94, -1));

        jLY.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLY.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLY, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 141, -1));

        jLBrigada.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLBrigada.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLBrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 525, -1));

        jLDetalle.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLDetalle.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 594, 90));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Fecha resolucion: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));
        getContentPane().add(jDCFecha_resol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 244, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Calificacion de exito:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 437, -1, 30));

        jRB1.setText("1");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB1, org.jdesktop.beansbinding.ELProperty.create("1"), jRB1, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jRB10.setText("10");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB10, org.jdesktop.beansbinding.ELProperty.create("10"), jRB10, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Finalizar Siniestro");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 590, 20));

        jRB2.setText("2");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB2, org.jdesktop.beansbinding.ELProperty.create("2"), jRB2, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jRB3.setText("3");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB3, org.jdesktop.beansbinding.ELProperty.create("3"), jRB3, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jRB4.setText("4");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB4, org.jdesktop.beansbinding.ELProperty.create("4"), jRB4, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jRB5.setText("5");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB5, org.jdesktop.beansbinding.ELProperty.create("5"), jRB5, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jRB6.setText("6");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB6, org.jdesktop.beansbinding.ELProperty.create("6"), jRB6, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jRB7.setText("7");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB7, org.jdesktop.beansbinding.ELProperty.create("7"), jRB7, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        jRB8.setText("8");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB8, org.jdesktop.beansbinding.ELProperty.create("8"), jRB8, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        jRB9.setText("9");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB9, org.jdesktop.beansbinding.ELProperty.create("9"), jRB9, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jRB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-más-50.png"))); // NOI18N
        jButton1.setText("Cerrar Siniestro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int calificacion = -1;

        LocalDate fecha_resol;

        if (jDCFecha_resol.getDate() == null) {
            JOptionPane.showMessageDialog(null, "No se puede finalizar un siniestro sin fecha de resolución.", "Error", 0);
            return;
        } else {
            fecha_resol = jDCFecha_resol.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        if (botones.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "No se puede finalizar un siniestro sin calificación de éxito.", "Error", 0);
            return;
        }

        if (fecha_resol.isAfter(LocalDate.now())) {
            JOptionPane.showMessageDialog(null, "La fecha colocada es posterior a la fecha de hoy.", "Error", 0);
            return;
        }

        calificacion = Integer.parseInt(botones.getSelection().getActionCommand());

        int respuesta;

        respuesta = JOptionPane.showConfirmDialog(
                null,
                "¿Desea finalizar el siniestro ID: " + jLID.getText() + "?\nFecha: " + fecha_resol + "\nCalificacion: " + calificacion,
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.ERROR_MESSAGE
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            SiniestroData siniestroData = new SiniestroData();
            Siniestro siniestro = siniestroData.siniestroPorID(idSiniestro);
            siniestro.setPuntuacion(calificacion);
            siniestro.setFechaResolucion(fecha_resol);
            siniestro.setEstado(false);

            siniestroData.modificarSiniestro(siniestro);
        }

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CerrarSiniestroPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CerrarSiniestroPuntuacion dialog = new CerrarSiniestroPuntuacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDCFecha_resol;
    private javax.swing.JLabel jLBrigada;
    private javax.swing.JLabel jLDetalle;
    private javax.swing.JLabel jLEmergencia;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLX;
    private javax.swing.JLabel jLY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRB1;
    private javax.swing.JRadioButton jRB10;
    private javax.swing.JRadioButton jRB2;
    private javax.swing.JRadioButton jRB3;
    private javax.swing.JRadioButton jRB4;
    private javax.swing.JRadioButton jRB5;
    private javax.swing.JRadioButton jRB6;
    private javax.swing.JRadioButton jRB7;
    private javax.swing.JRadioButton jRB8;
    private javax.swing.JRadioButton jRB9;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
