/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.CuartelData;
import Entidades.Cuartel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Li Donni
 */
public class CuartelUIModificar extends javax.swing.JDialog {

    private int idCuartel;

    /**
     * Creates new form CuartelUIModificar
     */
    public CuartelUIModificar(java.awt.Frame parent, boolean modal,int idCuartel) {
        super(parent, modal);
        initComponents();
        this.idCuartel=idCuartel;
        cargarCuartel();
    }

    private CuartelUIModificar(JFrame jFrame, boolean b) {
        
    }

    public void setIdCuartel(int idCuartel){
        this.idCuartel=idCuartel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextDireccion = new javax.swing.JTextField();
        jTextCoordX = new javax.swing.JTextField();
        jTextCodigo = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextCoordY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtnSalir = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioBtnEstado = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDireccionKeyTyped(evt);
            }
        });

        jTextCoordX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextCoordX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCoordXKeyTyped(evt);
            }
        });

        jTextCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextCodigo.setEnabled(false);
        jTextCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCodigoKeyTyped(evt);
            }
        });

        jTextEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextEmailKeyTyped(evt);
            }
        });

        jTextTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelefonoKeyTyped(evt);
            }
        });

        jTextCoordY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextCoordY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCoordYKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Modificar Cuartel:");

        jbtnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salir-50.png"))); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.setPreferredSize(new java.awt.Dimension(147, 35));
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-guardar-50.png"))); // NOI18N
        jbtnGuardar.setText("Modificar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Dirección");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Coordenda Y");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Coordenada X");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Telefono");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Estado");

        jRadioBtnEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Codigo");

        jTextNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jbtnGuardar)
                        .addGap(103, 103, 103)
                        .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextDireccion)
                        .addComponent(jTextEmail)
                        .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextCoordX)
                        .addComponent(jTextCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioBtnEstado)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioBtnEstado))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardar)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //CARGO LOS DATOS DEL CUARTEL A MODIFICAR
    public void cargarCuartel() {

        if (idCuartel != -1) {
            Cuartel cuartel = new Cuartel();
            CuartelData cuartelData = new CuartelData();
            cuartel = cuartelData.buscarCuartel(idCuartel);
            jTextCodigo.setText(String.valueOf(cuartel.getCodCuartel()));
            jTextNombre.setText(cuartel.getNombreCuartel());
            jTextDireccion.setText(cuartel.getDireccion());
            jTextEmail.setText(cuartel.getCorreo());
            jTextTelefono.setText(cuartel.getTelefono());
            jTextCoordX.setText(String.valueOf(cuartel.getCoordX()));
            jTextCoordY.setText(String.valueOf(cuartel.getCoordY()));
            jRadioBtnEstado.setSelected(cuartel.isEstado());
        } else {
            JOptionPane.showMessageDialog(this, "Error al cargar Cuartel");
            jbtnGuardar.setEnabled(false);
        }

    }

    //VALIDO EL FORMATO DEL EMAIL
    public boolean validarEmail(String email) {
        // Patrón de expresión regular para validar un email
        String patronEmail = "^[A-Za-z0-9+_.-]+@(.+)$";
        // Compila el patrón en un objeto Pattern
        Pattern pattern = Pattern.compile(patronEmail);
        // Crea un objeto Matcher
        Matcher matcher = pattern.matcher(email);
        // Comprueba si el email cumple con el patrón
        return matcher.matches();
    }

    private void jTextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDireccionKeyTyped
        if (jTextDireccion.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextDireccionKeyTyped

    private void jTextCoordXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCoordXKeyTyped
        int key = evt.getKeyChar(); // guardo el codigo ASCII que genero el evento
        boolean numero = key >= 48 && key <= 57 && jTextCoordX.getText().length() <= 10; //verifco si es un numero
        if (!numero) {
            evt.consume();  // NO LO ESCRIBE
        }
    }//GEN-LAST:event_jTextCoordXKeyTyped

    private void jTextCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigoKeyTyped
        if (jTextCodigo.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextCodigoKeyTyped

    private void jTextEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyTyped
        if (jTextEmail.getText().length() >= 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextEmailKeyTyped

    private void jTextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefonoKeyTyped
        if (jTextTelefono.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextTelefonoKeyTyped

    private void jTextCoordYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCoordYKeyTyped
        int key = evt.getKeyChar(); // guardo el codigo ASCII que genero el evento
        boolean numero = key >= 48 && key <= 57 && jTextCoordX.getText().length() <= 10; //verifco si es un numero
        if (!numero) {
            evt.consume();  // NO LO ESCRIBE
        }
    }//GEN-LAST:event_jTextCoordYKeyTyped

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed

        //VERIFICO SI TODOS LOS CAMPOS ESTAN COMPLETOS
        if ((jTextNombre.getText().length() > 0) && (jTextDireccion.getText().length() > 0) && (jTextTelefono.getText().length() > 0)
                && (jTextEmail.getText().length() > 0) && (jTextCoordX.getText().length() > 0) && (jTextCoordY.getText().length() > 0)) {

            if (validarEmail(jTextEmail.getText())) {
                Cuartel cuartel = new Cuartel(Integer.valueOf(jTextCodigo.getText()),jTextNombre.getText(), jTextDireccion.getText(), Integer.valueOf(jTextCoordX.getText()),
                        Integer.valueOf(jTextCoordY.getText()), jTextTelefono.getText(), jTextEmail.getText(), jRadioBtnEstado.isSelected());
                CuartelData cuartelData = new CuartelData();
                cuartelData.modificarCuartel(cuartel);//AGREGO EL CUARTEL
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "El formato del email no es valido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Se deben completar todos los campos");
        }

    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
      if (jTextCodigo.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuartelUIModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuartelUIModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuartelUIModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuartelUIModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CuartelUIModificar dialog = new CuartelUIModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioBtnEstado;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCoordX;
    private javax.swing.JTextField jTextCoordY;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnSalir;
    // End of variables declaration//GEN-END:variables
}
