/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BomberoData;
import AccesoADatos.BrigadaData;
import AccesoADatos.CuartelData;
import AccesoADatos.SiniestroData;
import Entidades.Bombero;
import Entidades.Brigada;
import Entidades.Cuartel;
import Entidades.Siniestro;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class HistoricoDeSiniestros extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel(){ // Creo un modelo de tabla
        public boolean isCellEditable(int f, int c){
            return false; // Indica que todas las celdas de la tabla no son editables
        }
    };
    
    /**
     * Creates new form HistoricoDeSiniestros
     */
    public HistoricoDeSiniestros() {
        initComponents();
        cabeceraDeTabla();
        limpiarTabla();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jsFecha = new javax.swing.JSlider();

        setClosable(true);
        setTitle("Historico de Siniestros");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Historico de Siniestros");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ayer");

        jBtnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salir-50.png"))); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Hoy");

        jsFecha.setMaximum(1);
        jsFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsFechaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jsFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel3))))
                .addContainerGap(675, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jsFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsFechaMouseClicked
        // TODO add your handling code here:
        limpiarTabla();
        cargarTabla();
    }//GEN-LAST:event_jsFechaMouseClicked

    private void cabeceraDeTabla(){
        //Nombre de columnas
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Fecha de registro");
        modeloTabla.addColumn("Tipo de Emergencia");
        modeloTabla.addColumn("Brigada");
        modeloTabla.addColumn("Cuartel");
        modeloTabla.addColumn("Fecha de resolución");
        modeloTabla.addColumn("Puntuación");
        jTable.setModel(modeloTabla);
        //Ancho de columnas
        jTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTable.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTable.getColumnModel().getColumn(5).setPreferredWidth(90);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(10);
    }
    
    private void cargarDatosEnLaTabla(Siniestro siniestro){
        modeloTabla.addRow(new Object[]{siniestro.getCodigo(), siniestro.getFecha(), siniestro.getTipoEmergencia().getEmergencia(), brigada(siniestro.getCodBrigada()), cuartel(siniestro.getCodBrigada()), siniestro.getFechaResolucion(), (siniestro.getPuntuacion()==0)?"":siniestro.getPuntuacion()});
    }
    
    public String brigada(int codigo){
        BrigadaData brigadadata = new BrigadaData();
        Brigada brigada = new Brigada();
        brigada = brigadadata.brigadaPorId(codigo);
        return brigada.getNombreBrigada();
    }
    
    public String cuartel(int codigo){
        BrigadaData brigadadata = new BrigadaData();
        Brigada brigada = new Brigada();
        brigada = brigadadata.brigadaPorId(codigo);
        CuartelData cuartelData = new CuartelData();
        Cuartel cuartel = new Cuartel();
        cuartel = cuartelData.buscarCuartel(brigada.getNumeroCuartel());
        return cuartel.getNombreCuartel();
    }
    
    public void limpiarTabla(){
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int filas = jTable.getRowCount()-1;
        for (int i = filas; i >= 0; i--) {          
            model.removeRow(model.getRowCount()-1);
        }
    }
    
    public void cargarTabla(){
        ArrayList<Siniestro> listaSiniestros = new ArrayList<Siniestro>();
        SiniestroData siniestroData = new SiniestroData();
        listaSiniestros = siniestroData.listarSiniestro();
        if (listaSiniestros.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existen siniestros en la base de datos", "MENSAJE", 1);
        } else {
            for (Siniestro siniestro : listaSiniestros) {
                switch(jsFecha.getValue()){ //Seleccion de Fecha
                    case 1: //Hoy
                        if (siniestro.getFecha().equals(LocalDate.now()))
                            cargarDatosEnLaTabla(siniestro);
                        break;
                    case 0: //Ayer
                        LocalDate hoy = LocalDate.now();
                        LocalDate ayer = hoy.minusDays(1); 
                        if (siniestro.getFecha().equals(ayer))
                            cargarDatosEnLaTabla(siniestro);
                        break;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JSlider jsFecha;
    // End of variables declaration//GEN-END:variables
}
