/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BrigadaData;
import AccesoADatos.CuartelData;
import Entidades.Brigada;
import com.sun.javafx.collections.ArrayListenerHelper;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author Natasha
 */
public class ListaBrigada extends javax.swing.JInternalFrame {

    int idBrigada;
    
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) { //SOBREESCRIBO EL METODO PARA QUE NO SE PUEDA EDITAR
            return false;
        }

    };

    /**
     * Creates new form Brigada
     */
    public ListaBrigada() {
        initComponents();
        armarCabecera();
        borrarFilas();
        cargoTabla();
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
    }
// cargo info en la tabla 

    public void cargoTabla() {
        BrigadaData brigadaData = new BrigadaData();
        ArrayList<Brigada> listaBrigada = new ArrayList();
        listaBrigada = brigadaData.listarBrigadas();
        if (listaBrigada.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existen brigadas en la base de datos", "MENSAJE", 1);
        } else {
            for (Brigada brigada : listaBrigada) {
                modelo.addRow(new Object[]{brigada.getCodigoBrigada(), brigada.getNombreBrigada(), brigada.getEspecialidad(),
                    (brigada.isEstado()) ? "Activa" : "Inactiva", cuartel(brigada.getNumeroCuartel())});
            }
        }
    }
    
    private String cuartel(int id){
        CuartelData cuartelData = new CuartelData();
        return cuartelData.buscarCuartel(id).getNombreCuartel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        JLListas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDeBrigada = new javax.swing.JTable();
        jBAgregar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setClosable(true);
        setTitle("Brigadas");

        JLListas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JLListas.setText("Lista de Brigadas");

        jTablaDeBrigada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablaDeBrigada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaDeBrigadaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaDeBrigada);

        jBAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-más-50.png"))); // NOI18N
        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-editar-50.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-basura-501.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salir-50.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLListas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jBSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(JLListas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int nroBrigada;
        int filaSeleccionada = -1;
        filaSeleccionada = jTablaDeBrigada.getSelectedRow();
        if (filaSeleccionada != -1) {
            nroBrigada = (Integer) jTablaDeBrigada.getValueAt(filaSeleccionada, 0);
        } else {
            nroBrigada = -1;
        }

        Frame f = JOptionPane.getFrameForComponent(this);
        ModificarBrigada ventanaModificar = new ModificarBrigada(f, true, nroBrigada);
        ventanaModificar.setVisible(true);
        int x = (this.getWidth() - ventanaModificar.getWidth()) / 2;
        int y = (this.getHeight() - ventanaModificar.getHeight()) / 2;
        ventanaModificar.setLocation(x, y);
        borrarFilas();
        cargoTabla();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la Brigada seleccionado? ", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            //BORRO EL CUARTEL
            BrigadaData brigadaData = new BrigadaData();
            brigadaData.eliminarBrigada(idBrigada);
            borrarFilas();
            cargoTabla();
            jBModificar.setEnabled(false);
            jBEliminar.setEnabled(false);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        AgregarBrigada ventaAgregar = new AgregarBrigada(f, true);
        ventaAgregar.setVisible(true);
        borrarFilas();
        cargoTabla();
        int x = (this.getWidth() - ventaAgregar.getWidth()) / 2;
        int y = (this.getHeight() - ventaAgregar.getHeight()) / 2;
        ventaAgregar.setLocation(x, y);
    }//GEN-LAST:event_jBAgregarActionPerformed
    private void borrarFilas() {
        int filas = jTablaDeBrigada.getRowCount() - 1;
        for (int f = filas; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
    private void jTablaDeBrigadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaDeBrigadaMouseClicked
        int filaSeleccionada = -1;
        filaSeleccionada = jTablaDeBrigada.getSelectedRow();
        if (filaSeleccionada != -1) {
            idBrigada = (Integer) jTablaDeBrigada.getValueAt(filaSeleccionada, 0);
            jBModificar.setEnabled(true);
            String estado = (String) jTablaDeBrigada.getValueAt(filaSeleccionada, 3);            
            if (estado.equals("Activa")) {
                jBEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTablaDeBrigadaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLListas;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaDeBrigada;
    // End of variables declaration//GEN-END:variables
private void armarCabecera() {

        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Estado");
        modelo.addColumn("Cuartel");
        jTablaDeBrigada.setModel(modelo);
        //Ancho de columnas
        jTablaDeBrigada.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTablaDeBrigada.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTablaDeBrigada.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTablaDeBrigada.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTablaDeBrigada.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

}
